Repository googleapis/python-bigquery-datatransfer, pull requests merged in 2020-09, with the labels that each got.

#44 fix: add dataset id in function call
  samples/create_scheduled_query.py
Labels: cla: yes

#47 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#48 chore: change default retry policies timeouts (via synth)
  .github/snippet-bot.yml
  docs/conf.py
  google/cloud/bigquery_datatransfer.py
  google/cloud/bigquery_datatransfer_v1/__init__.py
  google/cloud/bigquery_datatransfer_v1/gapic/data_transfer_service_client.py
  google/cloud/bigquery_datatransfer_v1/gapic/data_transfer_service_client_config.py
  google/cloud/bigquery_datatransfer_v1/gapic/enums.py
  google/cloud/bigquery_datatransfer_v1/gapic/transports/data_transfer_service_grpc_transport.py
  google/cloud/bigquery_datatransfer_v1/proto/datatransfer_pb2.py
  google/cloud/bigquery_datatransfer_v1/proto/datatransfer_pb2_grpc.py
  google/cloud/bigquery_datatransfer_v1/proto/transfer_pb2.py
  google/cloud/bigquery_datatransfer_v1/proto/transfer_pb2_grpc.py
  google/cloud/bigquery_datatransfer_v1/types.py
  noxfile.py
  scripts/decrypt-secrets.sh
  synth.metadata
  synth.py
  tests/unit/gapic/v1/test_data_transfer_service_client_v1.py
Labels: api: bigquerydatatransfer, cla: yes

#54 chore: Release v1.1.1
  CHANGELOG.md
  setup.py
Labels: autorelease: pending, cla: yes

#58 chore: Release v2.0.0
  CHANGELOG.md
Labels: autorelease: pending, cla: yes

#62 chore: Release v2.1.0
  CHANGELOG.md
  setup.py
Labels: autorelease: pending, cla: yes
