Repository googleapis/python-bigquery-datatransfer, pull requests merged in 2020-12, with the labels that each got.

#74 chore: require samples checks
  .github/sync-repo-settings.yaml
Labels: api: bigquerydatatransfer, cla: yes, samples

#73 chore: start tracking obsolete files
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#72 test: test with Python 3.9
  google/cloud/bigquery_datatransfer_v1/services/data_transfer_service/async_client.py
  google/cloud/bigquery_datatransfer_v1/services/data_transfer_service/transports/base.py
  synth.metadata
Labels: api: bigquerydatatransfer, automerge, cla: yes, context: partial

#77 chore: sort exception types
  google/cloud/bigquery_datatransfer_v1/services/data_transfer_service/async_client.py
  google/cloud/bigquery_datatransfer_v1/services/data_transfer_service/transports/base.py
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: none

#84 fix: remove recv msg limit, add enums to `types`
  google/cloud/bigquery_datatransfer_v1/services/data_transfer_service/transports/__init__.py
  google/cloud/bigquery_datatransfer_v1/services/data_transfer_service/transports/grpc.py
  google/cloud/bigquery_datatransfer_v1/services/data_transfer_service/transports/grpc_asyncio.py
  google/cloud/bigquery_datatransfer_v1/types/__init__.py
  synth.metadata
  tests/unit/gapic/bigquery_datatransfer_v1/test_data_transfer_service.py
Labels: api: bigquerydatatransfer, cla: yes, context: full

#83 docs: add scheduled query samples
  samples/snippets/conftest.py
  samples/snippets/copy_dataset_test.py
  samples/snippets/manage_transfer_configs.py
  samples/snippets/manage_transfer_configs_test.py
  samples/snippets/noxfile_config.py
  samples/snippets/quickstart_test.py
  samples/snippets/scheduled_query.py
  samples/snippets/scheduled_query_test.py
  samples/tests/__init__.py
  samples/tests/conftest.py
  samples/tests/test_update_transfer_config.py
Labels: api: bigquerydatatransfer, cla: yes, samples

#86 docs: remove redundant samples
  samples/__init__.py
  samples/create_scheduled_query.py
  samples/noxfile.py
  samples/requirements-test.txt
  samples/requirements.txt
  samples/update_transfer_config.py
Labels: api: bigquerydatatransfer, cla: yes, samples

#88 test: add system tests for mTLS testing
  tests/system.py
Labels: api: bigquerydatatransfer, cla: yes

#87 chore(deps): update precommit hook pre-commit/pre-commit-hooks to v3.4.0
  .pre-commit-config.yaml
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#89 docs(python): document adding Python 3.9 support, dropping 3.5 support
  CONTRIBUTING.rst
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#91 chore: exclude `.nox` directories from linting
  .flake8
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full
