Repository googleapis/python-bigquery-datatransfer, pull requests merged in 2020-10, with the labels that each got.

#53 fix!: avoid collision with built-in functions by renaming type property to type_
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.8/common.cfg
  google/cloud/bigquery_datatransfer_v1/services/data_transfer_service/client.py
  google/cloud/bigquery_datatransfer_v1/types/datatransfer.py
  samples/AUTHORING_GUIDE.md
  samples/CONTRIBUTING.md
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: partial

#65 chore(python): use 'setup.py' to detect repo root
  samples/noxfile.py
  samples/snippets/noxfile.py
  synth.metadata
Labels: cla: yes, context: full

#68 chore: standardize bigquerydatatransfer_update_config region tag
  samples/update_transfer_config.py
Labels: cla: yes
