Repository googleapis/python-bigquery-datatransfer, pull requests merged in 2021-03, with the labels that each got.

#110 test: install pyopenssl for mtls testing
  noxfile.py
  synth.metadata
Labels: api: bigquerydatatransfer, automerge, cla: yes, context: full

#113 chore: add pre-commit-config to renovate ignore paths
  renovate.json
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#115 build(python): fail nox sessions if a python version is missing
  noxfile.py
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#114 feat: add `client_cert_source_for_mtls` parameter to grpc transport
  google/cloud/bigquery_datatransfer_v1/services/data_transfer_service/async_client.py
  google/cloud/bigquery_datatransfer_v1/services/data_transfer_service/client.py
  google/cloud/bigquery_datatransfer_v1/services/data_transfer_service/pagers.py
  google/cloud/bigquery_datatransfer_v1/services/data_transfer_service/transports/grpc.py
  google/cloud/bigquery_datatransfer_v1/services/data_transfer_service/transports/grpc_asyncio.py
  google/cloud/bigquery_datatransfer_v1/types/__init__.py
  synth.metadata
  synth.py
  tests/unit/gapic/bigquery_datatransfer_v1/__init__.py
  tests/unit/gapic/bigquery_datatransfer_v1/test_data_transfer_service.py
Labels: api: bigquerydatatransfer, automerge, cla: yes, context: full

#117 build: exclude README from generated code
  synth.py
Labels: api: bigquerydatatransfer, cla: yes

#118 chore: use latest sphinx
  noxfile.py
  synth.py
Labels: api: bigquerydatatransfer, cla: yes

#122 test: check minimum dependency versions
  .pre-commit-config.yaml
  noxfile.py
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full
