Repository googleapis/python-bigquery-datatransfer, pull requests merged in 2021-01, with the labels that each got.

#92 chore: add constraints file
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  testing/constraints-3.6.txt
  testing/constraints-3.7.txt
  testing/constraints-3.8.txt
  testing/constraints-3.9.txt
Labels: api: bigquerydatatransfer, cla: yes

#95 docs: ensure minimum width for 'Parameters' / 'Returns' column
  LICENSE
  docs/_static/custom.css
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#100 build: migrate to flakybot
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
Labels: api: bigquerydatatransfer, automerge, cla: yes
